import type { GetServerSideProps, NextPage } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";
import { userSuccess } from "redux/slices/userSlice";
import { wrapper } from "redux/store";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>This is my first typescript app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps((store) => async (ctx) => {
    let session = await getSession(ctx);
    console.log("session got here =>", session);
    if (session) {
      store.dispatch(userSuccess(session));
    } else {
      return {
        props: {},
        redirect: {
          permanent: false,
          destination: "/login",
        }, // will be passed to the page component as props
      };
    }
  });
